travis:
  secure:
    BINSTAR_TOKEN: LSg1RF5o/Bt7dMCCfCPXDo8qHN3BSVrSjx4lczeXZUyQJZ+ghmxkJLoR6N7rcscYnKFTyT9M7LlLIEIWQX3V0hZ969bhmyh555HXcEVSAF1TQs99uoHSMJkn2OIEV5SYH/QhESVj1QPW+neXxneVYLFZNhnnWkB17QTF1hPh7Mdpwq9qG35fCZLHIUDHM08RoL/riahJwZOaaGhU/TZdVYzoVa9taZciH1DKb/7p1/oDDT5kdw3bx0KOM5uP05cpLHCqqvYoIwI0EQviXES9JE1Q4ivtpxHfzlL24W8276BHaHW0zkx2snjeYYe1gwfdbD9GMln0zoUISC4YTYAab+nmRJTMNFd0mM6TgNfqoZiC9KyRJUQpwwJ+AADxQY6totXjUGYWJo9djRC4dFgwVR3Jfj/M7DqkT8f9Fo7O7737XXZbvpsZg6c6fzrYgJHmnhB63D+u2kl6K7X8CHkKyzM+bT4Gb+jHWv6Y3i4s2MCJlK3GjOCrn77Doo24BNDu1qzhSfmsO5TN7Cj+u/2Xq3H8zoBFH30tlmJZw4dErgM9Fj/mxNA4/1ADxq1UVTJ01Ng/SwdFsjbydJottMedSMHxHqRrh7LPw/LWSBsDzdjyGY06rfr3tuQTQtWNb92IzylusBzJhphPvEn84LJ2hSBv3cQMLXp4zpZA2wSqWV8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
